services:
  api-server:
    build: # Dockerfile 이 있는 경로
      context: .
      dockerfile: ./Dockerfile-prod # Dockerfile 명시
    ports:
      - 8080:8080
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      cache-server:
        condition: service_healthy # cache-server 가 정상적으로 실행된 후에 백엔드 서버를 실행
  cache-server:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10