spring:
  profiles:
    default: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://host.docker.internal:3306/redis # Spring Boot ???? ??? database ??
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: cache-server # compose.yml ? cache-server
      port: 6379

logging:
  level:
    org.springframework.cache: trace # Redis ?? ?? ??

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: instagram-cache-server.quucwe.ng.0001.apn2.cache.amazonaws.com # ElastiCache ? ?????
      port: 6379